=== JoseDiegoSD/DdS3_EsquemasXML/src/EsquemaCanciones.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="canciones">

        <xs:complexType>
            <xs:sequence>
                <xs:element name="cancion" type="tipocancion" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

    </xs:element>
    <xs:complexType name="tipocancion">
        <xs:sequence>
            <xs:element name="Duracion" type="xs:string" />
            <xs:element name="AnioLanzamiento" type="xs:string"/>
            <xs:element name="Detalles" type="TipoDetalles"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TipoDetalles">

        <xs:sequence>
            <xs:element name="Titulo" type="xs:string"/>
            <xs:element name="Compositores" type="TipoCompositores"/>
            <xs:element name="Productores" type="TipoProductores"/>
            <xs:element name="Sello" type="xs:string"/>
            <xs:element name="Artista" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TipoCompositores">
        <xs:sequence>
            <xs:element name="Compositor" type="persona" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TipoProductores">
        <xs:sequence>
            <xs:element name="Productor" type="persona" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="persona">
        <xs:sequence>
            <xs:element name="Nombres" type="xs:string"/>
            <xs:element name="Apellidos" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== JoseDiegoSD/DdS3_EsquemasXML/src/CancionesXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<canciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="EsquemaCanciones.xsd">

    <cancion>
        <Duracion>3:30</Duracion>
        <AnioLanzamiento>2005</AnioLanzamiento>
        <Detalles>
            <Titulo>Helena</Titulo>
            <Compositores>
                <Compositor>
                    <Nombres>Gerard</Nombres>
                    <Apellidos>Way</Apellidos>
                </Compositor>
            </Compositores>

            <Productores>
                <Productor>
                    <Nombres>Howard</Nombres>
                    <Apellidos>Benson</Apellidos>
                </Productor>
            </Productores>

            <Sello>Three Cheers for Sweet Revenge</Sello>
            <Artista>My chemicall romance</Artista>
        </Detalles>
    </cancion>

    <cancion>
        <Duracion>5:34</Duracion>
        <AnioLanzamiento>1970</AnioLanzamiento>
        <Detalles>
            <Titulo>El triste</Titulo>
            <Compositores>
                <Compositor>
                    <Nombres>Roberto</Nombres>
                    <Apellidos>Cantoral</Apellidos>
                </Compositor>
            </Compositores>
            <Productores>
                <Productor>
                    <Nombres>Mariano</Nombres>
                    <Apellidos>Perez</Apellidos>
                </Productor>
            </Productores>
            <Sello>RCA Victor</Sello>
            <Artista>Jose Jose</Artista>
        </Detalles>
    </cancion>

    <cancion>
        <Duracion>4:36</Duracion>
        <AnioLanzamiento>1969</AnioLanzamiento>
        <Detalles>
            <Titulo>My way</Titulo>
            <Compositores>
                <Compositor>
                    <Nombres>Claude</Nombres>
                    <Apellidos>Francois</Apellidos>
                </Compositor>
            </Compositores>
            <Productores>
                <Productor>
                    <Nombres>Don</Nombres>
                    <Apellidos>Costa</Apellidos>
                </Productor>
            </Productores>
            <Sello>Reprise records</Sello>
            <Artista>Frank Sinatra</Artista>
        </Detalles>
    </cancion>
</canciones>
